# Generated by Django 4.2.3 on 2023-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
