# Generated by Django 4.2.3 on 2023-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_table1_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='date',
            field=models.DateField(default='1997-09-08'),
            preserve_default=False,
        ),
    ]
